services:
  - type: web
    name: supply-chain-digital-twin
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Use pre-built static files instead of rebuilding
      # The static directory is already built and committed
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION  
        value: 18.17.0
